"""initial schema

Revision ID: 20260414_0001
Revises:
Create Date: 2026-04-14

Creates all 11 tables from openreversefeed.db.models via metadata.create_all.
Subsequent revisions should be autogenerated with `alembic revision --autogenerate`.
"""
from __future__ import annotations

from alembic import op

from openreversefeed.db import models  # noqa: F401 — populates metadata
from openreversefeed.db.session import Base

revision = "20260414_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
